/** Generated by DailyMath tools/generate-problem-dates.py from verified PDF headers.
 * Source/provenance: docs/dailymath-problem-dates-2026.json. No student data.
 */
const entries: Record<number, { year: number; day: number; date: string }> = {
  17405: { year: 2026, day: 1, date: "2026-03-16" },
  17407: { year: 2026, day: 2, date: "2026-03-17" },
  17409: { year: 2026, day: 3, date: "2026-03-18" },
  17411: { year: 2026, day: 4, date: "2026-03-19" },
  17413: { year: 2026, day: 5, date: "2026-03-20" },
  17415: { year: 2026, day: 6, date: "2026-03-23" },
  17442: { year: 2026, day: 7, date: "2026-03-24" },
  17444: { year: 2026, day: 8, date: "2026-03-25" },
  17446: { year: 2026, day: 9, date: "2026-03-26" },
  17448: { year: 2026, day: 10, date: "2026-03-27" },
  17450: { year: 2026, day: 11, date: "2026-03-30" },
  17452: { year: 2026, day: 12, date: "2026-03-31" },
  17472: { year: 2026, day: 13, date: "2026-04-01" },
  17474: { year: 2026, day: 14, date: "2026-04-02" },
  17476: { year: 2026, day: 15, date: "2026-04-03" },
  17478: { year: 2026, day: 16, date: "2026-04-06" },
  17505: { year: 2026, day: 17, date: "2026-04-07" },
  17507: { year: 2026, day: 18, date: "2026-04-08" },
  17509: { year: 2026, day: 19, date: "2026-04-09" },
  17511: { year: 2026, day: 20, date: "2026-04-10" },
  17513: { year: 2026, day: 21, date: "2026-04-28" },
  17515: { year: 2026, day: 22, date: "2026-05-06" },
  17570: { year: 2026, day: 23, date: "2026-05-07" },
  17572: { year: 2026, day: 24, date: "2026-05-08" },
  17574: { year: 2026, day: 25, date: "2026-05-11" },
  17576: { year: 2026, day: 26, date: "2026-05-12" },
  17578: { year: 2026, day: 27, date: "2026-05-13" },
  17606: { year: 2026, day: 28, date: "2026-05-14" },
  17608: { year: 2026, day: 29, date: "2026-05-15" },
  17610: { year: 2026, day: 30, date: "2026-05-18" },
  17612: { year: 2026, day: 31, date: "2026-05-19" },
  17614: { year: 2026, day: 32, date: "2026-05-20" },
  17616: { year: 2026, day: 33, date: "2026-05-21" },
  17618: { year: 2026, day: 34, date: "2026-05-22" },
};

export function verifiedProblemDate(
  postId: number,
  year: number | null,
  day: number | null,
): number | null {
  const entry = entries[postId];
  if (!entry || entry.year !== year || entry.day !== day) return null;
  return Date.parse(`${entry.date}T00:00:00+09:00`);
}
